export { default as Feed } from './screens/Feed/Feed'
export { default as Discover } from './screens/Discover/Discover'
export { default as Profile } from './screens/Profile/Profile'
export { default as Comments } from './screens/Comments/Comments'
export { default as CommentsHandle } from './screens/Comments/CommentsHandle'
export { default as CustomBottomTabs } from './CustomBottomTabs/CustomBottomTabs'
export { default as NavBar } from './NavBar/NavBar'
